document.write ('\n');
document.write ('<SCRIPT type="text/javascript"> \n');
document.write ('var TFSMFlash_PRETAG="";\n');
document.write ('var TFSMFlash_POSTTAG=""; \n');
document.write ('var TFSMFlash_VERSION="8"; \n');
document.write ('var TFSMFlash_WMODE="window"; \n');
document.write ('var TFSMFlash_OASCLICK="http://oascentral.businessweek.com/RealMedia/ads/click_lx.ads/businessweek.com/careers/L24/1129658167/Middle/BusWeek/SMU_63472_mg_300/SMU_63472_mg_300_MBA.html/4f37497464556747342f594142414b66";\n');
document.write ('var TFSMFlash_SWFCLICKVARIABLE="?clickTAG="+TFSMFlash_OASCLICK+"?http://clk.atdmt.com/RCM/go/bsnsnsmu0100000004rcm/direct/01/"; \n');
document.write ('var TFSMFlash_SWFFILE="http://imagec09.247realmedia.com/RealMedia/ads/Creatives/BusWeek/SMU_63472_mg_300/1_MBA_300x250.swf/1205517795"+TFSMFlash_SWFCLICKVARIABLE; \n');
document.write ('var TFSMFlash_FSCOMMAND=""; \n');
document.write ('var TFSMFlash_IMAGEALTERNATE="http://imagec09.247realmedia.com/RealMedia/ads/Creatives/BusWeek/SMU_63472_mg_300/1_MBA_300x250.gif/1205517795"; \n');
document.write ('var TFSMFlash_OASALTTEXT=""; \n');
document.write ('var TFSMFlash_OASTARGET="_blank"; \n');
document.write ('var TFSMFlash_OASPROTOCOL="http://"; \n');
document.write ('var TFSMFlash_OASDIM="WIDTH=');
document.write ("'");
document.write ('300');
document.write ("'");
document.write (' HEIGHT=');
document.write ("'");
document.write ('250');
document.write ("'");
document.write ('"; \n');
document.write ('var TFSMFlash_OASADID="OAS_RMF_Middle_FLASH"; \n');
document.write ('document.write(');
document.write ("'");
document.write ('<scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt src="http://imagec09.247realmedia.com/RealMedia/ads/Creatives/BusWeek/SMU_63472_mg_300/TFSMFlashWrapper204.js/1205517795"></scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt>');
document.write ("'");
document.write ('); \n');
document.write ('</SCRIPT>\n');
document.write ('\n');
document.write ('<NOSCRIPT>\n');
document.write ('<A HREF="http://oascentral.businessweek.com/RealMedia/ads/click_lx.ads/businessweek.com/careers/L24/1129658167/Middle/BusWeek/SMU_63472_mg_300/SMU_63472_mg_300_MBA.html/4f37497464556747342f594142414b66?http://clk.atdmt.com/RCM/go/bsnsnsmu0100000004rcm/direct/01/" TARGET="_blank"><IMG SRC="http://imagec09.247realmedia.com/RealMedia/ads/Creatives/BusWeek/SMU_63472_mg_300/1_MBA_300x250.gif/1205517795" WIDTH=');
document.write ("'");
document.write ('300');
document.write ("'");
document.write (' HEIGHT=');
document.write ("'");
document.write ('250');
document.write ("'");
document.write (' BORDER=0 ALT=""></a>\n');
document.write ('</NOSCRIPT>\n');
document.write ('\n');
