(function(){
var g=true,h=null,j=false,aa=(new Date).getTime(),k=function(a){var b=(new Date).getTime()-aa;b="&dtd="+(b<1000?b:"M");return a+b};var l=this,ba=function(a,b,c){a=a.split(".");c=c||l;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:(c[d]={})},n=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},o=function(a){return n(a)=="array"},ca=function(a){var b=n(a);return b=="array"||b=="object"&&typeof a.length=="number"},p=function(a){return typeof a=="string"},da=function(a){a=n(a);return a=="object"||
a=="array"||a=="function"};Math.floor(Math.random()*2147483648).toString(36);
var ea=function(a){var b=n(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);b=b=="array"?[]:{};for(var c in a)b[c]=ea(a[c]);return b}return a},fa=function(a,b){var c=a.v;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,c);c=d}b=a.z||b;a=a.w||a;var e=b||l;d=c?function(){var f=Array.prototype.slice.call(arguments);f.unshift.apply(f,c);return a.apply(e,f)}:function(){return a.apply(e,arguments)};d.v=c;d.z=b;d.w=a;return d},ga=Date.now||function(){return(new Date).getTime()},
q=function(a,b,c){ba(a,b,c)};function r(a,b){a=parseFloat(a);return isNaN(a)||a>1||a<0?b:a}function s(a,b){if(a=="true")return g;if(a=="false")return j;return b}function u(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var ha="pagead2.googlesyndication.com",ia="googleads.g.doubleclick.net",ja="pubads.g.doubleclick.net",ka="securepubads.g.doubleclick.net",la="partner.googleadservices.com",v=u("pagead2.googlesyndication.com",ha),ma=u("googleads.g.doubleclick.net",ia),na=u("pagead2.googlesyndication.com",ha);u("pubads.g.doubleclick.net",ja);u("partner.googleadservices.com",la);u("securepubads.g.doubleclick.net",ka);function w(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function oa(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return j;window.setTimeout(function(){e.appendChild(d)},0);return g}function pa(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function qa(a){if(a in ra)return ra[a];return ra[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var ra={};
function sa(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=h}return a.toString()}else if(qa("msie")&&!window.opera){b=h;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=
0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(f){}}if(b){a=b.GetVariable("$version").split(" ")[1];return a.replace(/,/g,".")}}return"0"}function x(a){var b=a.google_ad_format;if(b)return b.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function y(a){return!!a&&a.indexOf("_sdo")!=-1}
function z(a,b){var c=Math.random();if(c<b){b=Math.floor(c/b*a.length);return a[b]}return""}var ta=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen){a.u_h=window.screen.height;a.u_w=window.screen.width;a.u_ah=window.screen.availHeight;a.u_aw=window.screen.availWidth;a.u_cd=window.screen.colorDepth}if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length};var ua={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},va={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},wa=
{google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};function xa(a,b){try{return a.top.document.URL==b.URL}catch(c){}return j}function ya(a,b,c,d){c=c||a.google_ad_width;d=d||a.google_ad_height;if(xa(a,b))return j;var e=b.documentElement;if(c&&d){var f=1,i=1;if(a.innerHeight){f=a.innerWidth;i=a.innerHeight}else if(e&&e.clientHeight){f=e.clientWidth;i=e.clientHeight}else if(b.body){f=b.body.clientWidth;i=b.body.clientHeight}if(i>2*d||f>2*c)return j}return g}function za(a,b){for(var c in b)a["google_"+c]=b[c]}
function Aa(a,b){if(!b)return a.URL;return a.referrer}function Ba(a,b){if(!b&&a.google_referrer_url==h)return"0";else if(b&&a.google_referrer_url==h)return"1";else if(!b&&a.google_referrer_url!=h)return"2";else if(b&&a.google_referrer_url!=h)return"3";return"4"}function Ca(a,b,c,d){a.page_url=Aa(c,d);a.page_location=h}function Da(a,b,c,d){a.page_url=b.google_page_url;a.page_location=Aa(c,d)||"EMPTY"}
function Ea(a,b){var c={},d=ya(a,b,a.google_ad_width,a.google_ad_height);c.iframing=Ba(a,d);a.google_page_url?Da(c,a,b,d):Ca(c,a,b,d);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1000:h;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Fa(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=h;b.page_url=c;b.page_location=a.URL;b.last_modified_time=h;b.referrer_url=c;return b}
function Ga(a,b){b=Ha(a,b);za(a,b)}function Ha(a,b){return a=a.google_page_url==h&&Ia[b.domain]?Fa(b):Ea(a,b)}var Ia={};Ia["ad.yieldmanager.com"]=g;var Ja=document,Ka=s("false",j),La=s("false",j),Ma=s("false",j);s("false",j);var C=window;var Na=function(a,b,c){b=fa(b,l,a);a=window.onerror;window.onerror=b;try{c()}catch(d){c=d.toString();var e="";if(d.fileName)e=d.fileName;var f=-1;if(d.lineNumber)f=d.lineNumber;b=b(c,e,f);if(!b)throw d;}window.onerror=a};q("google_protectAndRun",Na);
var Pa=function(a,b,c,d){if(Math.random()<0.01){var e=Ja;a=["http://",v,"/pagead/gen_204","?id=jserror","&jscb=",Ka?1:0,"&jscd=",La?1:0,"&context=",w(a),"&msg=",w(b),"&file=",w(c),"&line=",w(d.toString()),"&url=",w(e.URL.substring(0,512)),"&ref=",w(e.referrer.substring(0,512))];a.push(Oa());pa(C,a.join(""))}return!Ma};q("google_handleError",Pa);
var Ra=function(a){Qa|=a},Qa=0,Oa=function(){var a=["&client=",w(C.google_ad_client),"&format=",w(C.google_ad_format),"&slotname=",w(C.google_ad_slot),"&output=",w(C.google_ad_output),"&ad_type=",w(C.google_ad_type)];return a.join("")};var D="",Ua=function(){if(window.google_ad_frameborder==h)window.google_ad_frameborder=0;if(window.google_ad_output==h)window.google_ad_output="html";if(y(window.google_ad_format)){var a=window.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(a){window.google_ad_width=parseInt(a[1],10);window.google_ad_height=parseInt(a[2],10);window.google_ad_output="html"}}window.google_ad_format=Sa(window.google_ad_format,window.google_ad_output,window.google_ad_width,window.google_ad_height,window.google_ad_slot,
!!window.google_override_format);D=window.google_ad_client||"";window.google_ad_client=Ta(window.google_ad_format,window.google_ad_client);Ga(window,document);if(window.google_num_slots_by_channel==h)window.google_num_slots_by_channel={};if(window.google_viewed_host_channels==h)window.google_viewed_host_channels={};if(window.google_num_slots_by_client==h)window.google_num_slots_by_client={};if(window.google_prev_ad_formats_by_region==h)window.google_prev_ad_formats_by_region={};if(window.google_prev_ad_slotnames_by_region==
h)window.google_prev_ad_slotnames_by_region={};if(window.google_correlator==h)window.google_correlator=(new Date).getTime();if(window.google_adslot_loaded==h)window.google_adslot_loaded={};if(window.google_adContentsBySlot==h)window.google_adContentsBySlot={};if(window.google_flash_version==h)window.google_flash_version=sa();if(window.google_new_domain_checked==h)window.google_new_domain_checked=0;if(window.google_new_domain_enabled==h)window.google_new_domain_enabled=0;if(!window.google_num_ad_slots)window.google_num_ad_slots=
0;if(!window.google_num_0ad_slots)window.google_num_0ad_slots=0;if(!window.google_num_sdo_slots)window.google_num_sdo_slots=0;window.google_ad_section=window.google_ad_section||window.google_ad_region||"";window.google_country=window.google_country||window.google_gl||"";a=(new Date).getTime();if(o(window.google_color_bg))window.google_color_bg=E(window.google_color_bg,a);if(o(window.google_color_text))window.google_color_text=E(window.google_color_text,a);if(o(window.google_color_link))window.google_color_link=
E(window.google_color_link,a);if(o(window.google_color_url))window.google_color_url=E(window.google_color_url,a);if(o(window.google_color_border))window.google_color_border=E(window.google_color_border,a);if(o(window.google_color_line))window.google_color_line=E(window.google_color_line,a)},Va=function(a){var b;for(b in ua)a[b]=h;for(b in va)a[b]=h;for(b in wa)a[b]=h;a.google_container_id=h;a.google_eids=h;a.google_ad_region=h;a.google_gl=h},E=function(a,b){Ra(2);return a[b%a.length]},Ta=function(a,
b){if(!b)return"";b=b.toLowerCase();return b=y(a)?Wa(b):Xa(b)},Xa=function(a){if(a&&a.substring(0,3)!="ca-")a="ca-"+a;return a},Wa=function(a){if(a&&a.substring(0,9)!="dist-aff-")a="dist-aff-"+a;return a},Sa=function(a,b,c,d,e,f){if(!a&&b=="html")a=c+"x"+d;return a=Ya(a,e,f)?a.toLowerCase():""},Ya=function(a,b,c){if(!a)return j;if(!b)return g;return c};var F=document,G=navigator,H=window;
function Za(){var a=F.cookie,b=Math.round((new Date).getTime()/1000),c=H.google_analytics_domain_name;c=typeof c=="undefined"?$a("auto"):$a(c);var d=a.indexOf("__utma="+c+".")>-1,e=a.indexOf("__utmb="+c)>-1,f=a.indexOf("__utmc="+c)>-1,i={},m=!!H&&!!H.gaGlobal;if(d){a=a.split("__utma="+c+".")[1].split(";")[0].split(".");i.sid=e&&f?a[3]+"":m&&H.gaGlobal.sid?H.gaGlobal.sid:b+"";i.vid=a[0]+"."+a[1];i.from_cookie=g}else{i.sid=m&&H.gaGlobal.sid?H.gaGlobal.sid:b+"";i.vid=m&&H.gaGlobal.vid?H.gaGlobal.vid:
(Math.round(Math.random()*2147483647)^ab()&2147483647)+"."+b;i.from_cookie=j}i.dh=c;i.hid=m&&H.gaGlobal.hid?H.gaGlobal.hid:Math.round(Math.random()*2147483647);return H.gaGlobal=i}
function ab(){var a=F.cookie?F.cookie:"",b=H.history.length,c,d=[G.appName,G.version,G.language?G.language:G.browserLanguage,G.platform,G.userAgent,G.javaEnabled()?1:0].join("");if(H.screen)d+=H.screen.width+"x"+H.screen.height+H.screen.colorDepth;else if(H.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c.screen.width+"x"+c.screen.height}d+=a;d+=F.referrer?F.referrer:"";for(a=d.length;b>0;)d+=b--^a++;return bb(d)}
function bb(a){var b=1,c=0,d;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function $a(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=F.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return bb(a.toLowerCase())};var cb={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function db(a){a=a.google_page_location||a.google_page_url;if(!a)return j;a=a.toString();if(a.indexOf("http://")==0)a=a.substring(7,a.length);else if(a.indexOf("https://")==0)a=a.substring(8,a.length);var b=a.indexOf("/");if(b==-1)b=a.length;a=a.substring(0,b);a=a.split(".");b=j;if(a.length>=3)b=a[a.length-3]in cb;if(a.length>=2)b=b||a[a.length-2]in cb;return b}
function eb(a,b,c){if(db(a)){a.google_new_domain_checked=1;return j}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){c="http://"+ma+"/pagead/test_domain.js";d="script";b.write("<"+d+' src="'+c+'"></'+d+">");a.google_new_domain_checked=1;return g}}return j}function fb(a){if(!db(a)&&a.google_new_domain_enabled==1)return"http://"+ma;return"http://"+na};document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);var gb=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},mb=function(a,b){if(b)return a.replace(hb,"&amp;").replace(ib,"&lt;").replace(jb,"&gt;").replace(kb,"&quot;");else{if(!lb.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(hb,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(ib,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(jb,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(kb,"&quot;");return a}},hb=/&/g,ib=/</g,jb=/>/g,kb=/\"/g,lb=/[&<>\"]/,pb=function(a){if(I(a,"&"))return"document"in l&&!I(a,"<")?
nb(a):ob(a);return a},nb=function(a){var b=l.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},ob=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){c=Number("0"+c.substr(1));if(!isNaN(c))return String.fromCharCode(c)}return b}})},qb=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=c==1?b:b.charAt(d);
if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},I=function(a,b){return a.indexOf(b)!=-1},sb=function(a,b){var c=0;a=gb(String(a)).split(".");b=gb(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;c==0&&e<d;e++){var f=a[e]||"",i=b[e]||"",m=new RegExp("(\\d*)(\\D*)","g"),t=new RegExp("(\\d*)(\\D*)","g");do{var A=m.exec(f)||["","",""],B=t.exec(i)||["","",""];if(A[0].length==0&&B[0].length==0)break;c=A[1].length==0?0:parseInt(A[1],10);var Zb=B[1].length==
0?0:parseInt(B[1],10);c=rb(c,Zb)||rb(A[2].length==0,B[2].length==0)||rb(A[2],B[2])}while(c==0)}return c},rb=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};ga();var J=function(a){this.u=a;this.i=[];this.p=this.h=0;this.d=[];this.n=j;this.A=""};J.prototype.s=function(a,b){var c=this.u[b],d=this.i;this.u[b]=function(e){if(e&&e.length>0){var f=e.length>1?e[1].url:h;d.push([a,pb(e[0].url),f])}c(e)}};J.prototype.r=function(){this.h++};J.prototype.o=function(){if(!this.n){oa("http://"+v+"/pagead/osd.js");this.n=g}};
J.prototype.j=function(a){if(this.h>0)for(var b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)b.item(c).name=="google_ads_frame"&&a(b.item(c),b.item(c).src)};
J.prototype.k=function(a){var b=this.i;if(b.length>0)for(var c=document.getElementsByTagName("a"),d=function(A,B){return A.innerHTML.indexOf(B)>0},e=0;e<c.length;e++)for(var f=0;f<b.length;f++)if(c.item(e).href==b[f][1]){var i=c.item(e).parentNode;if(b[f][2])for(var m=i,t=0;t<4;t++){if(d(m,b[f][2])){i=m;break}m=m.parentNode}a(i,b[f][0]);b.splice(f,1);break}};J.prototype.e=function(a){this.k(a);this.j(a)};J.prototype.b=function(a){this.p=a};J.prototype.g=function(){return this.p};
J.prototype.t=function(a){this.A=a};J.prototype.f=function(){return this.i.length+this.h};J.prototype.c=function(a){this.d=a};J.prototype.q=function(a,b){if(this.d.length>0){for(var c=0;c<this.d.length;c++)if(this.d[c]==a)if(a=="js")this.s(b,"google_ad_request_done");else a=="html"&&this.r();this.o()}};var tb=function(){window.__google_ad_urls||(window.__google_ad_urls=new J(window));return window.__google_ad_urls};q("Goog_AdSense_getAdAdapterInstance",tb);q("Goog_AdSense_OsdAdapter",J);
q("Goog_AdSense_OsdAdapter.prototype.numBlocks",J.prototype.f);q("Goog_AdSense_OsdAdapter.prototype.findBlocks",J.prototype.e);q("Goog_AdSense_OsdAdapter.prototype.getOsdMode",J.prototype.g);var ub=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else for(var d=a.length,e=p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},vb=function(a){if(o(a))return a.concat();else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var K=function(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0};K.prototype.clone=function(){return new K(this.x,this.y)};K.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var L=function(a,b){this.width=a;this.height=b};L.prototype.clone=function(){return new L(this.width,this.height)};L.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};L.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};L.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
L.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};L.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var wb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var M,xb,N,yb,zb,Ab,Bb,Cb,Db,Eb,Fb=function(){return l.navigator?l.navigator.userAgent:h},O=function(){return l.navigator},Gb=function(){Ab=zb=yb=N=xb=M=j;var a;if(a=Fb()){var b=O();M=a.indexOf("Opera")==0;xb=!M&&a.indexOf("MSIE")!=-1;yb=(N=!M&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Ab=(zb=!M&&!N&&b.product=="Gecko")&&b.vendor=="Camino"}};Gb();
var P=M,Q=xb,Hb=zb,R=N,Ib=yb,Jb=function(){var a=O();return a&&a.platform||""},Kb=Jb(),Lb=function(){Bb=I(Kb,"Mac");Cb=I(Kb,"Win");Db=I(Kb,"Linux");Eb=!!O()&&I(O().appVersion||"","X11")};Lb();
var Mb=Bb,Nb=Cb,Ob=Db,Pb=function(){var a="",b;if(P&&l.opera){a=l.opera.version;a=typeof a=="function"?a():a}else{if(Hb)b=/rv\:([^\);]+)(\)|;)/;else if(Q)b=/MSIE\s+([^\);]+)(\)|;)/;else if(R)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(Fb()))?a[1]:""}return a},Qb=Pb(),Rb={},S=function(a){return Rb[a]||(Rb[a]=sb(Qb,a)>=0)};var T;var Sb=function(a){return p(a)?document.getElementById(a):a},Tb=Sb,Vb=function(a,b){wb(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Ub)a.setAttribute(Ub[d],c);else a[d]=c})},Ub={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},Wb=function(a){var b=a.document;if(R&&!S("500")&&!Ib){if(typeof a.innerHeight==
"undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new L(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"&&(!P||P&&S("9.50"))?b.documentElement:b.body;return new L(a.clientWidth,a.clientHeight)},Xb=function(a){a=!R&&a.compatMode=="CSS1Compat"?a.documentElement:a.body;return new K(a.scrollLeft,a.scrollTop)},$b=function(){return Yb(document,arguments)},Yb=function(a,b){var c=b[0],d=b[1];if(Q&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',
mb(d.name),'"');if(d.type){c.push(' type="',mb(d.type),'"');d=ea(d);delete d.type}c.push(">");c=c.join("")}var e=a.createElement(c);if(d)if(p(d))e.className=d;else Vb(e,d);if(b.length>2){function f(i){if(i)e.appendChild(p(i)?a.createTextNode(i):i)}for(d=2;d<b.length;d++){c=b[d];ca(c)&&!(da(c)&&c.nodeType>0)?ub(ac(c)?vb(c):c,f):f(c)}}return e},bc=function(a,b){a.appendChild(b)},cc=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):h},dc=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,
b)},ec=R&&S("522"),fc=function(a,b){if(typeof a.contains!="undefined"&&!ec&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},U=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},ac=function(a){if(a&&typeof a.length=="number")if(da(a))return typeof a.item=="function"||typeof a.item=="string";else if(n(a)=="function")return typeof a.item=="function";return j},
V=function(a){this.a=a||l.document||document};V.prototype.createElement=function(a){return this.a.createElement(a)};V.prototype.createTextNode=function(a){return this.a.createTextNode(a)};V.prototype.m=function(){return this.a.compatMode=="CSS1Compat"};V.prototype.l=function(){return Xb(this.a)};V.prototype.appendChild=bc;V.prototype.removeNode=cc;V.prototype.replaceNode=dc;V.prototype.contains=fc;var gc,hc,ic,jc,kc,lc,mc=function(){lc=kc=jc=ic=hc=gc=j;var a=Fb();if(a)if(a.indexOf("Firefox")!=-1)gc=g;else if(a.indexOf("Camino")!=-1)hc=g;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)ic=g;else if(a.indexOf("Android")!=-1)jc=g;else if(a.indexOf("Chrome")!=-1)kc=g;else if(a.indexOf("Safari")!=-1)lc=g};mc();var nc=function(a,b){var c=U(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(a=c.defaultView.getComputedStyle(a,""))return a[b];return h},W=function(a,b){return nc(a,b)||(a.currentStyle?a.currentStyle[b]:h)||a.style[b]},oc=function(a){a=a?a.nodeType==9?a:U(a):document;if(Q&&!(a?new V(U(a)):T||(T=new V)).m())return a.body;return a.documentElement},pc=function(a){var b=a.getBoundingClientRect();if(Q){a=a.ownerDocument;b.left-=a.documentElement.clientLeft+a.body.clientLeft;b.top-=a.documentElement.clientTop+
a.body.clientTop}return b},qc=function(a){if(Q)return a.offsetParent;var b=U(a),c=W(a,"position"),d=c=="fixed"||c=="absolute";for(a=a.parentNode;a&&a!=b;a=a.parentNode){c=W(a,"position");d=d&&c=="static"&&a!=b.documentElement&&a!=b.body;if(!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"))return a}return h},rc=function(a){var b,c=U(a),d=W(a,"position"),e=Hb&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||
b.screenY<0),f=new K(0,0),i=oc(c);if(a==i)return f;if(a.getBoundingClientRect){b=pc(a);a=(c?new V(U(c)):T||(T=new V)).l();f.x=b.left+a.x;f.y=b.top+a.y}else if(c.getBoxObjectFor&&!e){b=c.getBoxObjectFor(a);a=c.getBoxObjectFor(i);f.x=b.screenX-a.screenX;f.y=b.screenY-a.screenY}else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;if(b!=a){f.x+=b.clientLeft||0;f.y+=b.clientTop||0}if(R&&W(b,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(P||R&&d=="absolute")f.y-=
c.body.offsetTop;for(b=a;(b=qc(b))&&b!=c.body&&b!=i;){f.x-=b.scrollLeft;if(!P||b.tagName!="TR")f.y-=b.scrollTop}}return f},sc=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;b=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return b}},tc=function(a){var b=U(a),c="";if(b.createTextRange){c=b.body.createTextRange();c.moveToElementText(a);c=c.queryCommandValue("FontName")}if(!c){c=W(a,"fontFamily");if(P&&
Ob)c=c.replace(/ \[[^\]]*\]/,"")}a=c.split(",");if(a.length>1)c=a[0];return qb(c,"\"'")},uc=function(a){return(a=a.match(/[^\d]+$/))&&a[0]||h},vc={cm:1,"in":1,mm:1,pc:1,pt:1},wc={em:1,ex:1},xc=function(a){var b=W(a,"fontSize"),c=uc(b);if(b&&"px"==c)return parseInt(b,10);if(Q)if(c in vc)return sc(a,b,"left","pixelLeft");else if(a.parentNode&&a.parentNode.nodeType==1&&c in wc){a=a.parentNode;c=W(a,"fontSize");return sc(a,b==c?"1em":b,"left","pixelLeft")}c=$b("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});
bc(a,c);b=c.offsetHeight;cc(c);return b};var X={};function yc(a){if(a==1)return g;return!X[a]}function Y(a,b){if(a)if(b==1)if(X[b])X[b]+=","+a;else X[b]=a;else X[b]=a}function zc(){var a=[];for(var b in X)a.push(X[b]);return a.join(",")}function Ac(a,b){if(a&&a instanceof Array)for(var c=0;c<a.length;c++)a[c]&&typeof a[c]=="string"&&Y(a[c],b)}var Z=j;
function Bc(a,b){var c="script";Z=Cc(a,b);if(!Z)a.google_allow_expandable_ads=j;var d=!Dc();Z&&d&&b.write("<"+c+' src="http://'+v+'/pagead/expansion_embed.js"></'+c+">");a=eb(a,b,r("1",0.01));(d=d||a)&&qa("msie")&&!window.opera?b.write("<"+c+' src="http://'+v+'/pagead/render_ads.js"></'+c+">"):b.write("<"+c+'>google_protectAndRun("ads_core.google_render_ad", google_handleError, google_render_ad);</'+c+">")}function $(a){return a!=h?'"'+a+'"':'""'}
function Ec(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}var Fc=function(a,b){var c=b.slice(-1);c=c=="?"||c=="#"?"":"&";b=[b];for(var d in a){var e=a[d];if(e||e===0||e===j){if(typeof e=="boolean")e=e?1:0;b.push(c,d,"=",w(e));c="&"}}return b.join("")};function Gc(){var a=Q&&S("6"),b=Hb&&S("1.8.1"),c=R&&S("525");if(Nb&&(a||b||c))return g;else if(Mb&&(c||b))return g;else if(Ob&&b)return g;return j}
function Dc(){return(typeof ExpandableAdSlotFactory=="function"||typeof ExpandableAdSlotFactory=="object")&&typeof ExpandableAdSlotFactory.createIframe=="function"}function Cc(a,b){if(a.google_allow_expandable_ads===j||!b.body||a.google_ad_output!="html"||ya(a,b)||!Hc(a)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!Gc())return j;return g}function Hc(a){var b=a.google_ad_format;if(y(b))return j;if(x(a)&&!(b=="468x15_0ads_al"))return j;return g}
function Ic(){var a;if(C.google_ad_output=="html"&&!(x(C)||y(C.google_ad_format))&&yc(0)){a=["6083035","6083034"];a=z(a,r("0",0));Y(a,0)}return a=="6083035"}function Jc(a,b){if((a.google_unique_id||0)==0&&a.google_ad_output=="html"&&document.body&&typeof b.body.getBoundingClientRect=="function")return z(["36812001","36812002"],r("0.01",0));return""}
function Kc(a,b){var c="";if(a.google_num_ad_slots==0){if(!(x(a)||y(a.google_ad_format)))if(b=="html")c=z(["36815001","36815002"],r("0.006",0));else if(b=="js")c=z(["36815003","36815004"],r("0.006",0));if(c==""&&(b=="html"||b=="js"))c=z(["36813005","36813006"],r("0.008",0))}return c}
function Lc(a,b){b.t(a);switch(a){case "36815004":b.b(1);b.c(["js"]);break;case "36815002":b.b(1);b.c(["html"]);break;case "36813006":b.b(0);b.c(["html","js"]);break}}function Mc(a){if(a.body)try{return Wb(window)}catch(b){return new L(-12245933,-12245933)}else return new L(-1,-1)}
function Nc(a,b,c,d){var e=Ec(a);c=Fc({ifi:e},c);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+$(k(c))+"></"+f+">");else if(a.google_ad_output=="html")if(Z&&Dc()){b=a.google_container_id||d||h;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+e,k(c),a.google_ad_width,a.google_ad_height,
b)}else{c='<iframe name="google_ads_frame" width='+$(a.google_ad_width)+" height="+$(a.google_ad_height)+" frameborder="+$(a.google_ad_frameborder)+" src="+$(k(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?Oc(a.google_container_id,b,c):b.write(c)}}function Pc(a){Va(a)}function Qc(a,b){if(!Rc())return j;var c=Ic();a=Sc(a,b);c=fb(window)+Tc(a.google_ad_format,c);window.google_ad_url=Fc(a,c);return g}
var Wc=function(a){a.dt=aa;var b=window.google_prev_ad_formats_by_region,c=window.google_ad_section,d=window.google_ad_format,e=window.google_ad_slot;if(b[c])if(!y(d)){a.prev_fmts=b[c];if(window.google_num_slots_by_client.length>1)a.slot=window.google_num_slots_by_client[D]}var f=window.google_prev_ad_slotnames_by_region;if(f[c])a.prev_slotnames=f[c].toLowerCase();if(d){if(!y(d))if(b[c])b[c]+=","+d;else b[c]=d}else if(e)if(f[c])f[c]+=","+e;else f[c]=e;a.correlator=window.google_correlator;if(window.google_new_domain_checked==
1&&window.google_new_domain_enabled==0)a.dblk=1;if(window.google_ad_channel){b=window.google_num_slots_by_channel;c="";d=window.google_ad_channel.split(Uc);for(e=0;e<d.length;e++){f=d[e];if(b[f])c+=f+"+";else b[f]=1}a.pv_ch=c}if(window.google_ad_host_channel){b=Vc(window.google_ad_host_channel,window.google_viewed_host_channels);a.pv_h_ch=b}if(Ka)a.jscb=1;if(La)a.jscd=1;a.frm=window.google_iframing;b=Za();a.ga_vid=b.vid;a.ga_sid=b.sid;a.ga_hid=b.hid;a.ga_fc=b.from_cookie;a.ga_wpids=window.google_analytics_uacct},
Xc=function(a,b,c){var d;if(b)if(typeof a.getBoundingClientRect=="function"){a=a.getBoundingClientRect();d={x:a.left,y:a.top}}else{d={};d.x="-252738";d.y="-252738"}else try{d=rc(a)}catch(e){d={};d.x="-252738";d.y="-252738"}if(d){c.adx=d.x;c.ady=d.y}},Yc=function(a){var b=Mc(document);if(b){a.biw=b.width;a.bih=b.height}};
function Vc(a,b){var c=a.split("|");a=-1;for(var d=[],e=0;e<c.length;e++){var f=c[e].split(Uc);b[e]||(b[e]={});for(var i="",m=0;m<f.length;m++){var t=f[m];if(!(t==""))if(b[e][t])i+="+"+t;else b[e][t]=1}i=i.slice(1);d[e]=i;if(i!="")a=e}b="";if(a>-1){for(e=0;e<a;e++)b+=d[e]+"|";b+=d[a]}return b}
function Zc(){var a=tb(),b=window.google_enable_osd,c="";if(b===g){c="36813006";Lc(c,a)}else if(b!==j&&yc(0)){c=z(["68120011","68120021","68120031","68120041"],r("0",0));if(c==""){c=Jc(window,document);if(c==""){c=Kc(window,window.google_ad_output);c!=""&&Lc(c,a)}}}Y(c,0);var d=j;var e=b=j;switch(c){case "68120031":e=g;case "68120021":b=g;case "68120041":d=g;break;case "36812002":if(!window.google_atf_included){window.google_atf_included=g;oa("http://"+v+"/pagead/atf.js")}break}var f;
if(d){var i="google_temp_span";f=window.google_container_id&&Tb(window.google_container_id)||Tb(i);if(!f&&!window.google_container_id){document.write("<span id="+i+"></span>");f=Tb(i)}}c=j;c=b?Qc(f,e):Qc();f&&f.id==i&&cc(f);if(c){a.q(window.google_ad_output,window.google_ad_url);Nc(window,document,window.google_ad_url);Pc(window)}}var $c=function(a){var b;for(b in va)a[va[b]]=window[b];for(b in ua)a[ua[b]]=window[b];for(b in wa)a[wa[b]]=window[b]},ad=function(a){Ac(window.google_eids,1);a.eid=zc()};
function bd(a,b,c,d){a=Pa(a,b,c,d);Bc(window,document);return a}function cd(){Ua()}function dd(a){var b={};a=a.split("?");a=a[a.length-1].split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=d.length>1?window.decodeURIComponent?decodeURIComponent(d[1].replace(/\+/g," ")):unescape(d[1]):""}catch(e){}}return b}function ed(){var a=window,b=dd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}
function Oc(a,b,c){if(a)if((a=b.getElementById(a))&&c&&c.length!=""){a.style.visibility="visible";a.innerHTML=c}}
var Tc=function(a,b){return a=y(a)?"/pagead/sdo?":b?"/pagead/render_iframe_ads.html#":"/pagead/ads?"},fd=function(a,b){b.dff=tc(a);b.dfs=xc(a)},Rc=function(){var a=window.google_prev_ad_formats_by_region,b=window.google_prev_ad_slotnames_by_region,c=window.google_ad_section;if(y(window.google_ad_format)){window.google_num_sdo_slots+=1;if(window.google_num_sdo_slots>4)return j}else if(x(window)){window.google_num_0ad_slots+=1;if(window.google_num_0ad_slots>3)return j}else{window.google_num_ad_slots+=
1;if(window.google_num_slots_to_rotate){Ra(1);a[c]=h;b[c]=h;if(window.google_num_slot_to_show==h)window.google_num_slot_to_show=(new Date).getTime()%window.google_num_slots_to_rotate+1;if(window.google_num_slot_to_show!=window.google_num_ad_slots)return j}else if(window.google_num_ad_slots>6&&c=="")return j}a=window.google_num_slots_by_client;if(a[D])a[D]+=1;else{a[D]=1;a.length+=1}return g},Sc=function(a,b){var c={};$c(c);Wc(c);ta(c);if(a){fd(a,c);Xc(a,!!b,c)}Yc(c);ad(c);c.fu=Qa;return c},Uc=/[+, ]/;
window.google_render_ad=Zc;var gd=["30143070","30143071","30143075"],hd=typeof window.postMessage=="function"||typeof window.postMessage=="object"||typeof document.postMessage=="function",jd=function(a,b){typeof A1_googleCreateSlot=="function"?A1_googleCreateSlot(a.google_ad_client):id(a,b)},ld=function(){if(!kd())return j;return g},md=function(a){if(y(a.google_ad_format))return j;var b=a.google_ad_output;if(b&&b!="html")return j;a=a.google_ad_client;if(typeof a!="string"||a.substring(0,4)!="pub-"&&a.substring(0,7)!="ca-pub-")return j;
return g},od=function(a){if(typeof a.google_a1_eid=="string")return a.google_a1_eid;var b=r("0.001",0);a.google_a1_eid=nd(gd,b);return a.google_a1_eid},id=function(a,b){if(!a.google_included_a1_script){var c="script",d="/pagead/show_ads_sra3.js?v\x3d1";b.write("<"+c+' src="http://'+v+d+'"></'+c+">");a.google_included_a1_script=g}},kd=function(){if(Q&&S("8"))return j;return hd||!R},nd=function(a,b){var c=Math.random();if(c<b){b=Math.floor(c/b*a.length);return a[b]}return""};function pd(){ed();Na("show_ads.google_init_globals",bd,cd);Bc(window,document)}function qd(){if(!ld(window)||!md(window))pd();else if(Ma&&window.google_use_a1===g)jd(window,document);else{var a=od(window);if(a){Y(a,0);window.google_allow_expandable_ads=j}!a||a=="30143070"?pd():jd(window,document)}}Na("show_ads.main",Pa,qd);
})()
